{{if .Values.Identity -}}
---
###
### Identity Controller Service
###
{{ if and (.Values.Identity.Issuer) (eq .Values.Identity.Issuer.IssuerType "linkerd") -}}
{{ if and (.Values.LinkerdIdentityIssuer) (eq .Values.LinkerdIdentityIssuer.Scheme "linkerd.io/tls") -}}
---
kind: Secret
apiVersion: v1
metadata:
  name: linkerd-identity-issuer
  namespace: {{.Values.Namespace}}
  labels:
    {{.Values.ControllerComponentLabel}}: identity
    {{.Values.ControllerNamespaceLabel}}: {{.Values.Namespace}}
  annotations:
    {{.Values.CreatedByAnnotation}}: {{default (printf "linkerd/helm %s" .Values.LinkerdVersion) .Values.CliVersion}}
    {{- if .Values.LinkerdIdentityIssuer.CrtExpiryAnnotation}}
    {{.Values.LinkerdIdentityIssuer.CrtExpiryAnnotation}}: {{required "Please provide the identity issuer certificate expiry date" .Values.LinkerdIdentityIssuer.CrtExpiry}}
    {{- end}}
data:
  crt.pem: {{b64enc (required "Please provide the identity issuer certificate" .Values.LinkerdIdentityIssuer.TLS.CrtPEM | trim)}}
  key.pem: {{b64enc (required "Please provide the identity issue private key" .Values.LinkerdIdentityIssuer.TLS.KeyPEM | trim)}}
{{- end}}
{{- end}}
---
kind: Service
apiVersion: v1
metadata:
  name: linkerd-identity
  namespace: {{.Values.Namespace}}
  labels:
    {{.Values.ControllerComponentLabel}}: identity
    {{.Values.ControllerNamespaceLabel}}: {{.Values.Namespace}}
  annotations:
    {{.Values.CreatedByAnnotation}}: {{default (printf "linkerd/helm %s" .Values.LinkerdVersion) .Values.CliVersion}}
spec:
  type: ClusterIP
  selector:
    {{.Values.ControllerComponentLabel}}: identity
  ports:
  - name: grpc
    port: 8080
    targetPort: 8080
---
{{ $_ := set .Values.Proxy "WorkloadKind" "deployment" -}}
{{ $_ := set .Values.Proxy "Component" "linkerd-identity" -}}
{{ include "linkerd.proxy.validation" .Values.Proxy -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    {{.Values.CreatedByAnnotation}}: {{default (printf "linkerd/helm %s" .Values.LinkerdVersion) .Values.CliVersion}}
  labels:
    {{.Values.ControllerComponentLabel}}: identity
    {{.Values.ControllerNamespaceLabel}}: {{.Values.Namespace}}
  name: linkerd-identity
  namespace: {{.Values.Namespace}}
spec:
  replicas: {{.Values.ControllerReplicas}}
  selector:
    matchLabels:
      {{.Values.ControllerComponentLabel}}: identity
      {{.Values.ControllerNamespaceLabel}}: {{.Values.Namespace}}
      {{- include "partials.proxy.labels" .Values.Proxy | nindent 6}}
  template:
    metadata:
      annotations:
        {{.Values.CreatedByAnnotation}}: {{default (printf "linkerd/helm %s" .Values.LinkerdVersion) .Values.CliVersion}}
        {{- include "partials.proxy.annotations" .Values.Proxy| nindent 8}}
      labels:
        {{.Values.ControllerComponentLabel}}: identity
        {{.Values.ControllerNamespaceLabel}}: {{.Values.Namespace}}
        {{- include "partials.proxy.labels" .Values.Proxy | nindent 8}}
    spec:
      {{- include "linkerd.node-selector" . | nindent 6 }}
      {{- if .Values.EnablePodAntiAffinity -}}
      {{- $local := dict "Component" "identity" "Label" .Values.ControllerComponentLabel -}}
      {{- include "linkerd.pod-affinity" $local | nindent 6 -}}
      {{- end }}
      containers:
      - args:
        - identity
        - -log-level={{.Values.ControllerLogLevel}}
        {{- include "partials.linkerd.trace" . | nindent 8 -}}
        image: {{.Values.ControllerImage}}:{{default .Values.LinkerdVersion .Values.ControllerImageVersion}}
        imagePullPolicy: {{.Values.ImagePullPolicy}}
        livenessProbe:
          httpGet:
            path: /ping
            port: 9990
          initialDelaySeconds: 10
        name: identity
        ports:
        - containerPort: 8080
          name: grpc
        - containerPort: 9990
          name: admin-http
        readinessProbe:
          failureThreshold: 7
          httpGet:
            path: /ready
            port: 9990
        {{- if .Values.IdentityResources -}}
        {{- include "partials.resources" .Values.IdentityResources | nindent 8 }}
        {{- end }}
        securityContext:
          runAsUser: {{.Values.ControllerUID}}
        volumeMounts:
        - mountPath: /var/run/linkerd/config
          name: config
        {{- if eq .Values.Identity.Issuer.IssuerType "linkerd"}}
        - mountPath: /var/run/linkerd/identity/issuer
          name: identity-issuer
        {{- end }}
      - {{- include "partials.proxy" . | indent 8 | trimPrefix (repeat 7 " ") }}
      {{ if not .Values.NoInitContainer -}}
      initContainers:
      - {{- include "partials.proxy-init" . | indent 8 | trimPrefix (repeat 7 " ") }}
      {{ end -}}
      serviceAccountName: linkerd-identity
      volumes:
      - configMap:
          name: linkerd-config
        name: config
      {{ if eq .Values.Identity.Issuer.IssuerType "linkerd" -}}
      - name: identity-issuer
        secret:
          secretName: linkerd-identity-issuer
      {{ end -}}
      - {{- include "partials.proxy.volumes.identity" . | indent 8 | trimPrefix (repeat 7 " ") }}
{{end -}}
